### ISSUE TITLE
License

### ISSUE THREAD

**Issue by comradekingu** [languages-in-floss/site#1]
This should have a license.
AGPLv3+ should do, and hopefully CC-BY-SA can be avoided for the Weblate translation.

**Comment by Jibec** [comment]
Well, the content itself is under CC-BY SA 3.0 (you see it in https://languages-in-floss.eu)

I do not understand the Weblate reference, what is the impact?
I'm wondering if code and content should use different licenses.

**Comment by comradekingu** [comment]
The BY-part isn't transferable, and a pain to deal with.
There is no "COPYING" or "LICENSE" file in the repo.

**Comment by Jibec** [comment]
license is set in LICENSE file for the code. Each content page has CC-BY-SA 4.0.
I don't quite understand what's the BY issue, please add references if you think it might be an issue. But as far it is used by both GNOME and Fedora projects for documentation, I doubt they would have miss something like this.

**Comment by comradekingu** [comment]
The issue is having to cite who was involved for everything. BSD removed this in their revised license.
